### ISSUE TITLE
No such file or directory: 'probes/pytorch_alexnet_imagenet/html-features.html'

### ISSUE THREAD

**Issue by filltong** [CSAILVision/NetDissect#14]
script/rundissect_pytorch.sh: line 199: globexists: command not found
Generating graph
Traceback (most recent call last):
  File "src/graphprobe.py", line 114, in <module>
    stats = summarize(loadviz(directory, blob), args.threshold,
  File "src/graphprobe.py", line 20, in loadviz
    with open(html_fn) as f:
IOError: [Errno 2] No such file or directory: 'probes/pytorch_alexnet_imagenet/html-features.html'

**Comment by gauenk** [comment]
see issue #10 

this can be fixed by pasting the following code snippet into the `script/rundissect_pytorch.sh`
```
# For expanding globs http://stackoverflow.com/questions/2937407                
function globexists {                                                           
  set +f                                                                        
  test -e "$1" -o -L "$1";set -f                                                
} 
```
