### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by yuxin212** [CSAILVision/NetDissect#17]
Hi,

I tried your toolbox using my trained model and your broden dataset. I ran rundissect.sh, and I finally got this: 

Traceback (most recent call last):
  File "src/report.py", line 425, in <module>
    verbose=True)
  File "src/report.py", line 45, in generate_html_summary
    save=ed.filename('html/' + barfn))
  File "/home/cc/NetDissect-release1/src/bargraph.py", line 106, in bar_graph_svg
    barheight, barwidth, show_labels, filename)
  File "/home/cc/NetDissect-release1/src/bargraph.py", line 110, in make_svg_bargraph
    unitheight = float(barheight) / max(heights)
ValueError: max() arg is an empty sequence

Do you know how to fix this problem? Thank you.
b.t.w. there is no html folder under NetDissect.

**Comment by kathanvyas** [comment]
were you able to solve this error?

**Comment by yuxin212** [comment]
> were you able to solve this error?

no, i didn't solve this error

**Comment by andrewjmcgehee** [comment]
Does anyone have a solution to this error?
