### ISSUE TITLE
problem when use the pytorch version,have no idea with it

### ISSUE THREAD

**Issue by miss1997yuan** [CSAILVision/NetDissect#22]
Traceback (most recent call last):
  File "src/netprobe_pytorch.py", line 291, in <module>
    split=args.split, cl_args=args, verbose=True)
  File "src/netprobe_pytorch.py", line 52, in create_probe
    data = loadseg.SegmentationData(args.dataset)
  File "/home/czy/NetDissect/src/loadseg.py", line 63, in __init__
    self.image = [decode_index_dict(r) for r in DictUnicodeReader(f)]
  File "/home/czy/NetDissect/src/unicsv.py", line 48, in __init__
    self.reader = csv.DictReader(f, dialect=dialect, **kwds)
  File "/home/czy/.conda/envs/python36/lib/python3.6/csv.py", line 87, in __init__
    self.reader = reader(f, dialect, *args, **kwds)
TypeError: argument 1 must be an iterator

**Comment by cyizhuo** [comment]
Don't know if it helps or not, but I created conda env with:

conda install scipy==1.0.0 (must be installed first)
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch

and Net-Dissection-Lite worked perfect (on linux, never successed on windows).

**Comment by maduc7** [comment]
@miss1997yuan did you find any solution? I am facing the same error...
Thanks
