### ISSUE TITLE
call() got an unexpected keyword argument 'grid'

### ISSUE THREAD

**Issue by davidbau** [CSAILVision/NetDissect#5]
@lingeo writes: I ran the code just as the readme shown, while i got this srror:

Traceback (most recent call last):
File "src/labelprobe.py", line 306, in 
parallel=args.parallel)
File "src/labelprobe.py", line 101, in label_probe
thresh, labelcat, batch_size, ahead, verbose, parallel)
File "src/labelprobe.py", line 134, in fast_process
result.get(31536000)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
raise self._value
TypeError: call() got an unexpected keyword argument 'grid'

Is there anything wrong with my python2.7? or should I use the python3.5? and why?

**Comment by davidbau** [comment]
@lingeo.  The grid= parameter looks like it comes from the callable returned by scipy.interpolate.RectBivariateSpline - see https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.interpolate.RectBivariateSpline.html.

You'll want to make sure you are using a current version of scipy.  (Note that this function signature dates to about 4 years ago, so it looks like your scipy must be older than that.)
https://github.com/scipy/scipy/blame/1525688152a4e23cdd11476ba3768ab0e4769083/scipy/interpolate/fitpack2.py
